name: PortalBridge
version: ${version}
description: ${description}
main: ru.deelter.portalbridge.PortalBridgePlugin
api-version: "1.21"
author: Deelter
website: https://github.com/yourname/PortalBridge

commands:
  portal:
    description: Portal management
    usage: /portal <open|bind|hub|lobby|help|admin> [args]
    permission: portalbridge.use
    aliases: [p]

permissions:
  portalbridge.use:
    default: true
  portalbridge.bind:
    default: true
  portalbridge.admin:
    default: op
